[package]
name = "l3g5nd/networker"
description = "An easy to use Networking library for Roblox Lua."
version = "4.1.5"
license = "Apache-2.0"
authors = ["L3G5ND"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]